services:
  openresty:
    build:
      context: ./openresty
      dockerfile: Dockerfile
    ports:
      - "${HTTPS_PORT}:443"
      - "${HTTP_PORT}:80"
    volumes:
      - ./certs:/etc/ssl/private:ro
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./openresty/lab_access.conf:/etc/openresty/lab_access.conf:ro
      - ./openresty/lua:/etc/openresty/lua:ro
      - ./web:/var/www/html:ro
    environment:
      - GUAC_ADMIN_USER=${GUAC_ADMIN_USER}
      - GUAC_ADMIN_PASS=${GUAC_ADMIN_PASS}
      - SERVER_NAME=${SERVER_NAME}
      - ISSUER=${ISSUER}
    depends_on:
      guacamole:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f -L http://localhost:80/ -H 'Host: ${SERVER_NAME}' --connect-timeout 5 --insecure"]
      timeout: 10s
      retries: 3
      interval: 30s
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.3'
        reservations:
          memory: 64M
          cpus: '0.2'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        labels: "service=openresty"
    restart: always
    networks:
      - guacnet

  mysql:
    image: mysql:8.0.41
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/001-create-schema.sql:/docker-entrypoint-initdb.d/001-create-schema.sql:ro
      - ./mysql/002-create-admin-user.sql:/docker-entrypoint-initdb.d/002-create-admin-user.sql:ro
      - ./mysql/003-rdp-example.sql:/docker-entrypoint-initdb.d/003-rdp-example.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 60s  # MySQL needs time to initialize
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '0.75'
        reservations:
          memory: 384M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=mysql"
    #ports:
    # - "3306:3306"
    restart: always
    networks:
      - guacnet

  guacamole:
    build:
      context: ./guacamole
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
      guacd:
        condition: service_healthy
    environment:
      GUACD_HOSTNAME: guacd
    volumes:
      - ./guacamole/extensions:/etc/guacamole/extensions
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/guacamole/"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 120s  # Guacamole needs time to fully start
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
        labels: "service=guacamole"
    #ports:
    # - "8080:8080"
    networks:
      - guacnet
  guacd:
    image: guacamole/guacd
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4822"]
      timeout: 10s
      retries: 3
      interval: 30s
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.3'
        reservations:
          memory: 64M
          cpus: '0.2'
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
        labels: "service=guacd"
    restart: always
    #ports:
    # - "4822:4822"
    networks:
      - guacnet

networks:
  guacnet:
    driver: bridge

volumes:
  mysql_data:
